### ISSUE TITLE
Could not find a declaration file for module 'better-sqlite3-multiple-ciphers' node_modules/better-sqlite3-multiple-ciphers/lib/index.js' implicitly has an 'any' type

### ISSUE THREAD

**Issue by raphael10-collab** [m4heshd/better-sqlite3-multiple-ciphers#22]
`import Database from 'better-sqlite3-multiple-ciphers'` : 
    
    ERROR in src/main/index.ts:131:22
    TS7016: Could not find a declaration file for module 'better-sqlite3-multiple-ciphers'. '/home/raphy/Playground/node_modules/better-sqlite3-multiple-ciphers/lib/index.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/better-sqlite3-multiple-ciphers` if it exists or add a new declaration (.d.ts) file containing `declare module 'better-sqlite3-multiple-ciphers';`
        129 | //const infopiecesDb = new Database(infopiecesDbpath, { verbose: console.log })
        130 |
      > 131 | import Database from 'better-sqlite3-multiple-ciphers'

    "@types/better-sqlite3": "^7.5.0",
    "better-sqlite3": "^7.5.3",
    "better-sqlite3-multiple-ciphers": "^7.5.2",
    "electron": "17"
     node:  v16.15.0

I added in `src/type/type.d.ts` : 

    export {}
    
    declare global {
      declare module 'better-sqlite3-multiple-ciphers
    }

but still get the same error.

Is there any `@types/better-sqlite3-multiple-ciphers` ?

**Comment by m4heshd** [comment]
> Is there any `@types/better-sqlite3-multiple-ciphers` ?

Unfortunately I haven't had the time to do a PR for that. I'd love some help with this. Since the API is completely identical to `better-sqlite3`, all somebody will have to do is create a fork of `@types/better-sqlite3`, rename it to `better-sqlite3-multiple-ciphers` and just deal with the PR process of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by jasonk** [comment]
Since the API is identical you don't even have to go to the trouble of copying the types. You can just add `@types/better-sqlite3` as a devDependency and then add a types file like this:

```typescript
declare module 'better-sqlite3-multiple-ciphers' {
  import { BetterSqlite3 } from 'better-sqlite3';
  export default BetterSqlite3.DatabaseConstructor;
}
```

You also don't have to deal with the PR process of DefinitelyTyped, you can include the types in your own repo and publish them along with the library (which is the preferred method anyway, since you don't have to install a separate types library).
