### ISSUE TITLE
Error while signing windows .exe (electron-builder)

### ISSUE THREAD

**Issue by tobiasmuecksch** [m4heshd/better-sqlite3-multiple-ciphers#51]
## Error Message

```
Failed

Unrecognized file type: /Users/tmuecksch/Sites/bico/v2/ehinger-app-v2/bico-app/electron/dist/win-unpacked/resources/app.asar.unpacked/node_modules/better-sqlite3-multiple-ciphers/build/Release/test_extension.node
```

## Description

When I'm building my application with electron-builder for production; I also need to sign it (of course). This works perfectly fine for macOS. But it fails for windows.

To track this problem down, could you please explain to me what this file is for? Why is it called `test_extension`? Having `test` in it's name, seems to me as it shouldn't be there.
`better-sqlite3-multiple-ciphers/build/Release/test_extension.node`

## Screenshot

<img width="1138" alt="image" src="https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/1294854/9d929c11-721a-40e1-80aa-7e280c08ee1c">

## System Info

- Machine: MacBook Pro (M1 Pro, 2021)
- Operating System: macOS Ventura 13.4.1
- node: `v18.16.0`
- better-sqlite3-multiple-ciphers: `^8.4.0`
-  electron: `25.1.1`
- electron-builder: `24.4.0`

**Comment by m4heshd** [comment]
This is because you're trying to cross-build a native module.

While packaging, `electron-builder` automatically downloads the prebuilt binary for your target platform. If we didn't provide prebuilt binaries, your whole build process would fail. That download only contains the native library file `better_sqlite3.node`. What actually happens is it runs `electron-builder install-app-deps` under the hood and that process compiles the `test_extension.node`. It's only used for tests. It won't be created upon a typical installation.

All this means is that the `test_extension.node` is compiled for mac and `better_sqlite3.node` is compiled for the target platform. It's a complete mess. Yes, `electron-builder` can cross-compile but only when complex native modules aren't involved because `electron-builder` doesn't actually compile anything native. It's just a packager.

Moral of the story, never ever cross-build apps. Always use CI for that. [Take a look at our build workflow](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/blob/master/.github/workflows/prebuild.yml). This issue is the same reason why we go through all this trouble to build prebuilt binaries.

**Comment by tobiasmuecksch** [comment]
@m4heshd Thank you for your in-depth answer. I will revise my build process accordingly.

**Comment by willemdjong** [comment]
https://github.com/electron-userland/electron-builder/issues/7652 this is the reason why!
