### ISSUE TITLE
The file is not a database😕.

### ISSUE THREAD

**Issue by Vanillma** [m4heshd/better-sqlite3-multiple-ciphers#54]
Sorry that it took a long time for me to respond.

First, can I know more about your device? What arch is its CPU? Any chance it's emulated? (x86). Pre-built binaries are available for both `armv7` and `arm64`. So it's odd that your installation didn't download them automatically. Can you also check what [`os.platform()`](https://nodejs.org/api/os.html#osplatform) returns on your device? There's a chance it might return `android`, which would be a problem.

Second, this made me revisit the build configuration and realized that the `-march=native` flag isn't necessary. The problem is, I can't remember why exactly I added this flag. I only have a faint memory of `arm` builds failing to compile without it. I just removed the flag in https://github.com/m4heshd/better-sqlite3-multiple-ciphers/commit/4d6416efd0267715db46f4432f496fbdf2795fff, and you can check if it works now. I'm still skeptical about using Clang though. If you can, use GCC.

_Originally posted by @m4heshd in https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/53#issuecomment-1652065695_

Hi...I noticed that the flag is also in the beta version, please remove it from there if possible.

But I have a question for another problem!
I was able to create a database with table through the API and Multicipher...and also some rows of data.

but the problem is that when I try to open the database with Sqlcipher(on command line), it gives an error and says that it is not a database!

I first created the table with sqlcipher and then tried to connect with the API, I also tried the other way around.

but I always get the same error... is this the expected behavior?

**Comment by m4heshd** [comment]
1. Please don't quote old/closed issues in a new issue and mix up the context. It makes it very difficult for the maintainers to debug, for you to get an answer, and for the people who read this in the future. An old issue should only be mentioned in the context of your current issue has a relationship to that.
2. Please include some debug information, your code, or better, a minimal reproducible repo for your code so the maintainers can quickly debug the issue you're running into. Open-source maintainers hardly have any time to investigate things from scratch.
3. Always search for old issues before opening a new one because there's a high chance that your issue could already have been debugged in the past.

Continuing from that third point, the issue you're having is both [in the documentation](https://github.com/m4heshd/better-sqlite3-multiple-ciphers#encryption) and mentioned in multiple issues including [Issue #14](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/14#issuecomment-1073039266).
Closing the issue as a duplicate.

**Comment by Vanillma** [comment]
> 1. Please don't quote old/closed issues in a new issue and mix up the context. It makes it very difficult for the maintainers to debug, for you to get an answer, and for the people who read this in the future. An old issue should only be mentioned in the context of your current issue has a relationship to that.
> 2. Please include some debug information, your code, or better, a minimal reproducible repo for your code so the maintainers can quickly debug the issue you're running into. Open-source maintainers hardly have any time to investigate things from scratch.
> 3. Always search for old issues before opening a new one because there's a high chance that your issue could already have been debugged in the past.
> 
> Continuing from that third point, the issue you're having is both [in the documentation](https://github.com/m4heshd/better-sqlite3-multiple-ciphers#encryption) and mentioned in multiple issues including [Issue #14](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/14#issuecomment-1073039266). Closing the issue as a duplicate.

I'm so sorry.

But:
1- I have already used the reference feature in other repositories and they had no problem!

2- And Of Course, Github and Microsoft must have put that option for users to use...isn't that right???

In any case, you as the repository owner have options...such as deleting an issue completely...if you need to correct your issue history and are very concerned, please delete this issue completely.
