### ISSUE TITLE
The system is not compatible

### ISSUE THREAD

**Issue by jws2001** [m4heshd/better-sqlite3-multiple-ciphers#79]
node_modules/better-sqlite3-multiple-ciphers/build/Release/better_sqlite3.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by m4heshd** [comment]
Need much more information than that. Sounds like you're on an M-series Mac. Node version? Are you trying on Node or Electron? Platform, OS, reproducible repo. All of this information would be very helpful in debugging.

**Comment by jws2001** [comment]
![image](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/assets/54891248/1b226134-2f0b-490e-87c3-b08bef5b6ce6)

**Comment by jws2001** [comment]
macM1 system Electron

**Comment by m4heshd** [comment]
The problem here is that your node module installation seems to have run natively but the application itself is trying to run via Rosetta. It's a bit difficult to debug your specific issue since I don't use Mac but you need to figure out how to run your node instance natively. Alternatively, you can try the following instructions:

1. Install `node-gyp` on your project locally using `npm install node-gyp@latest`
2. Run the following command to recompile the module against `arm64` architecture.

```yml
node-gyp -C ./node_modules/better-sqlite3-multiple-ciphers/ clean configure --arch=arm64 rebuild
```
