### ISSUE TITLE
Add support for `win-arm64` prebuilt binaries

### ISSUE THREAD

**Issue by thecodrr** [m4heshd/better-sqlite3-multiple-ciphers#82]

**Comment by m4heshd** [comment]
Unfortunately, it's not possible at the moment due to GitHub not providing a Windows arm64 runner. You can keep track of https://github.com/actions/runner-images/issues/768 for updates.

**Comment by thecodrr** [comment]
@m4heshd maybe I am doing something wrong but I was able to generate an arm64 build of better-sqlite3-multiple-cipher on my on x86/x64 Windows PC using Visual Studio ARM build tools.

**Comment by m4heshd** [comment]
Just tested and this is technically possible now since Node has been providing Windows headers for `arm` since Node v20, at https://nodejs.org/dist/v20.0.0. But builds will still fail for Node v18. Electron however provided arm headers since v6.0.8. So electron builds seem to be fine.

I might add this feature but need to test it a lot before. I already tested all Electron versions and currently supported Node versions. Everything's fine except Node v18.

**Comment by thecodrr** [comment]
That's good to know.


In the meantime, I have forked this project since I need the ARM binaries for Electron quite urgently. I'll be keeping an eye out for when you release support for ARM builds so I can move back.

**Comment by m4heshd** [comment]
PR already created for the upstream at https://github.com/WiseLibs/better-sqlite3/pull/1141.

You can take a look at the tests here: https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/7853495517

**Comment by thecodrr** [comment]
Thanks for the quick response!

**Comment by m4heshd** [comment]
This feature is now available in [v9.4.1](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/releases/tag/v9.4.1).
Closing this.

**Comment by thecodrr** [comment]
@m4heshd thank you for adding this so quickly! Would it also be possible to add support for linux-arm64 prebuilds for electron?

**Comment by m4heshd** [comment]
We talked about that at BS3 but not feasible for the moment. It can be done, but due to the limitations of Qemu, it would take days for the workflow to finish if we do that. Have to wait for dedicated hardware. But who knows? This might be possible already 🤷🏻‍♂️. We just don't have enough time to put into research sadly.

**Comment by thecodrr** [comment]
@m4heshd positive development in this area: https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/

**Comment by m4heshd** [comment]
That is indeed great news. 🥳
